FROM mhart/alpine-node:9

LABEL maintainer="DevMountain"

WORKDIR /var/server

COPY package.json /var/server

COPY wait-for-postgres.sh /var/server

RUN apk --update add postgresql && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

RUN yarn

CMD ["./wait-for-postgres.sh", "postgresdb_server", "yarn", "dev"]